title: Resource Sharing in the times of COVID-19 (RSCVD)
description: IFLA Document Delivery and Resource Sharing Section Standing Committee has created this form to facilitate international resource sharing during COVID-19. <br><br> Only Interlibrary loan professionals working in non-for-profit libraries can make requests through this form.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
