title: IFLA DDRS Document Request Form
description: IFLA Document Delivery and Resource Sharing Section Standing Committee has created this form to facilitate international resource sharing during the times of COVID-19. <br><br> Only the Interlibrary loan professional working in non-for-profit libraries can make the request through this form.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
